;;; nndiscourse-test.el --- Native backend tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'nndiscourse)
(defmacro nndiscourse-test-with-db (&rest body)
  (declare (indent 0))
  `(let* ((directory (make-temp-file "nndiscourse-test-" t))
          (db (nndiscourse--load "https://example.org" (expand-file-name "state.json" directory)))
          (nndiscourse--state db)
          (auth-sources nil)
          (discourse-auth--credentials (make-hash-table :test #'equal)))
     (unwind-protect (progn ,@body) (delete-directory directory t))))
(defun nndiscourse-test-post (id floor &optional parent)
  (list :id id :post_number floor :topic_id 42 :reply_to_post_number parent
        :username "someone" :created_at "2026-10-01T12:00:00Z" :cooked "<p>正文</p>"))
(defun nndiscourse-test-topic ()
  (list :id 42 :title "Example" :post_stream
        (list :stream '(100 110 140) :posts (list (nndiscourse-test-post 100 1)))))
(ert-deftest nndiscourse-test-url-identity ()
  (dolist (url '("https://example.org/t/42" "https://example.org/t/42/7"
                 "https://example.org/t/slug/42/7?x=1" "https://example.org/t/slug/42.json"))
    (should (equal '("https://example.org" 42) (nndiscourse--location url))))
  (should (equal '("https://example.org:8443/forum" 42)
                 (nndiscourse--location "https://EXAMPLE.org:8443/forum/t/slug/42")))
  (dolist (url '("http://example.org/t/42" "https://user@example.org/t/42" "https://example.org/t/0"
                 "https://example.org/t/42/7/9" "https://example.org/t/slug/42\r\nInjected"))
    (should-error (nndiscourse--location url))))
(ert-deftest nndiscourse-test-pagination-and-native-headers ()
  (nndiscourse-test-with-db
    (let ((calls 0) failure)
      (cl-letf (((symbol-function 'nndiscourse--http)
                 (lambda (_db _method path fields callback)
                   (cl-incf calls)
                   (funcall callback
                            (if (equal path "/t/42.json") (nndiscourse-test-topic)
                              (should (equal path "/t/42/posts.json"))
                              (should (equal '(("post_ids[]" "110") ("post_ids[]" "140")) fields))
                              (list :post_stream (list :posts (list (nndiscourse-test-post 110 3 1)
                                                                  (nndiscourse-test-post 140 7 3))))) nil nil))))
        (nndiscourse-update "topic.42" nil (lambda (err) (setq failure err))))
      (should-not failure) (should (= calls 2))
      (let* ((group (nndiscourse--group db "topic.42"))
             (posts (plist-get group :posts))
             (header (nndiscourse--header db group (car (last posts)))))
        (should (equal '(1 3 7) (mapcar (lambda (p) (plist-get p :number)) posts)))
        (should (equal (nndiscourse--message-id db group 3) (mail-header-references header)))
        (should (equal (nndiscourse--db-groups db)
                       (nndiscourse--db-groups (nndiscourse--load "https://example.org" (nndiscourse--db-file db)))))
        (should (= #o600 (logand #o777 (file-modes (nndiscourse--db-file db)))))))))
(ert-deftest nndiscourse-test-partial-fetch-does-not-replace-cache ()
  (nndiscourse-test-with-db
    (let* ((group (nndiscourse--group db "topic.42" t)) failure)
      (setf (plist-get group :title) "Old snapshot")
      (cl-letf (((symbol-function 'nndiscourse--http)
                 (lambda (_db _method path _fields cb)
                   (funcall cb (if (equal path "/t/42.json") (nndiscourse-test-topic)
                                 '(:post_stream (:posts nil))) nil nil))))
        (nndiscourse-update "topic.42" nil (lambda (err) (setq failure err))))
      (should failure)
      (should (equal "Old snapshot" (plist-get (nndiscourse--group db "topic.42") :title)))
      (should-not (gethash "topic.42" (nndiscourse--db-busy db))))))
(ert-deftest nndiscourse-test-deleted-parent-and-high-water ()
  (nndiscourse-test-with-db
    (let* ((group (nndiscourse--group db "topic.42" t))
           (_ (setf (plist-get group :high) 99))
           (snapshot (nndiscourse--normalize db group "Title" (list (nndiscourse-test-post 140 7 3))))
           (parent (nndiscourse--post db snapshot 3)))
      (should (plist-get parent :missing))
      (should (= 99 (plist-get snapshot :high)))
      (should-not (equal (nndiscourse--message-id db snapshot 3)
                         (nndiscourse--message-id (make-nndiscourse--db :base "https://elsewhere.org") snapshot 3)))
      (should-error (nndiscourse--normalize db group "Title" (list (nndiscourse-test-post 140 7 7)))))))
(ert-deftest nndiscourse-test-scan-only-subscribed-topics ()
  (nndiscourse-test-with-db
    (nndiscourse--group db "topic.42" t) (nndiscourse--group db "topic.99" t)
    (let (scanned)
      (cl-letf (((symbol-function 'nndiscourse--select) (lambda (&rest _) db))
                ((symbol-function 'nndiscourse--subscribed-p) (lambda (group _) (equal group "topic.42")))
                ((symbol-function 'nndiscourse-update)
                 (lambda (group _server cb) (push group scanned) (funcall cb nil))))
        (should (nndiscourse-request-scan nil "example.org")))
      (should (equal '("topic.42") scanned)))))
(ert-deftest nndiscourse-test-http-credentials-and-destinations ()
  (nndiscourse-test-with-db
    (let ((calls 0) failure uncertain)
      (cl-letf (((symbol-function 'plz)
                 (lambda (_method _url &rest args)
                   (cl-incf calls)
                   (should-not (assoc "Cookie" (plist-get args :headers)))
                   (should-not (member "--location" plz-curl-default-args))
                   (funcall (plist-get args :then) (make-plz-response :status 200 :body "{}")))))
        (nndiscourse--http db 'get "/t/42.json" nil #'ignore)
        (nndiscourse--http db 'post "/posts.json" nil (lambda (_ e u) (setq failure e uncertain u)))
        (should failure) (should-not uncertain)
        (nndiscourse--http db 'get "https://evil.example" nil #'ignore)
        (should (= calls 1))))))
(ert-deftest nndiscourse-test-native-article-mime ()
  (nndiscourse-test-with-db
    (let* ((group (nndiscourse--normalize db (nndiscourse--group db "topic.42" t) "Title\nInjected: no"
                                        (list (nndiscourse-test-post 100 1)))))
      (setf (nndiscourse--db-groups db) (list group))
      (with-temp-buffer
        (should (equal '("topic.42" . 1) (nndiscourse-request-article 1 "topic.42" nil (current-buffer))))
        (should (string-match-p "Content-Transfer-Encoding: base64" (buffer-string)))
        (should-not (string-match-p "\nInjected:" (buffer-string)))
        (goto-char (point-min)) (search-forward "\n\n")
        (should (equal "<p>正文</p>" (decode-coding-string (base64-decode-string (buffer-substring (point) (point-max))) 'utf-8)))))))

(ert-deftest nndiscourse-test-reply-post-and-uncertain-lock ()
  (nndiscourse-test-with-db
    (let* ((group (nndiscourse--normalize db (nndiscourse--group db "topic.42" t) "Topic"
                                        (list (nndiscourse-test-post 100 1)
                                              (nndiscourse-test-post 110 3 1))))
           (calls 0))
      (setf (nndiscourse--db-groups db) (list group))
      (cl-letf (((symbol-function 'nndiscourse--http)
                 (lambda (_db method path fields callback)
                   (cl-incf calls)
                   (should (eq method 'post)) (should (equal path "/posts.json"))
                   (should (equal "42" (cadr (assoc "topic_id" fields))))
                   (should (equal "3" (cadr (assoc "reply_to_post_number" fields))))
                   (should (equal "中文 & text" (cadr (assoc "raw" fields))))
                   ;; Verify the durable pending lock exists before dispatch.
                   (should (equal "pending" (plist-get (car (nndiscourse--db-attempts
                                                            (nndiscourse--load "https://example.org" (nndiscourse--db-file db)))) :state)))
                   (funcall callback nil "timeout" t))))
        (should-error (nndiscourse--submit db group 3 nil "中文 & text"))
        (should-error (nndiscourse--submit db group 3 nil "中文 & text"))
        (should (= calls 1)))
      (should (equal "pending" (plist-get (car (nndiscourse--db-attempts db)) :state))))))

(ert-deftest nndiscourse-test-confirmed-reply-and-rejected-post ()
  (nndiscourse-test-with-db
    (let* ((group (nndiscourse--normalize db (nndiscourse--group db "topic.42" t) "Topic"
                                        (list (nndiscourse-test-post 100 1))))
           reject)
      (setf (nndiscourse--db-groups db) (list group))
      (cl-letf (((symbol-function 'nndiscourse--http)
                 (lambda (_db _method _path _fields callback)
                   (if reject (funcall callback nil "HTTP 422" nil)
                     (funcall callback (nndiscourse-test-post 200 2 1) nil nil)))))
        (should (equal 2 (plist-get (nndiscourse--submit db group 1 nil "first") :post_number)))
        (should (equal "sent" (plist-get (car (nndiscourse--db-attempts db)) :state)))
        (should-error (nndiscourse--submit db group 1 nil "first"))
        (setq reject t)
        (should-error (nndiscourse--submit db group 1 nil "second"))
        (should (equal "failed" (plist-get (car (nndiscourse--db-attempts db)) :state)))))))

(ert-deftest nndiscourse-test-new-topic-category-and-draft ()
  (nndiscourse-test-with-db
    (let ((posted nil))
      (cl-letf (((symbol-function 'nndiscourse--http)
                 (lambda (_db method path fields cb)
                   (pcase (list method path)
                     (`(get "/categories.json")
                      (funcall cb '(:category_list (:categories ((:id 5 :name "General")
                                                                (:id 8 :name "Help" :parent_category_id 5)))) nil nil))
                     (`(post "/posts.json")
                      (setq posted fields)
                      (funcall cb '(:id 201 :topic_id 99 :post_number 1) nil nil))))))
        (should (equal '(("General [5]" . 5) ("General / Help [8]" . 8))
                       (nndiscourse--categories db)))
        (should (equal 99 (plist-get (nndiscourse--submit db nil nil "Hello" "Body" 8) :topic_id)))
        (should (equal "8" (cadr (assoc "category" posted))))
        (should (equal "Hello" (cadr (assoc "title" posted))))))))

(ert-deftest nndiscourse-test-composer-rejects-attachments ()
  (with-temp-buffer
    (nndiscourse-compose-topic-mode)
    (insert "Subject: Example\n" mail-header-separator "\nBody text")
    (should (equal "Body text" (nndiscourse--body)))
    (goto-char (point-max)) (insert "\n<#part type=application/octet-stream>")
    (should-error (nndiscourse--body))))
