name: Emacs tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.4
      - name: Install plz
        run: |
          emacs --batch --eval '(require (quote package))' \
            --eval '(add-to-list (quote package-archives) (cons "melpa" "https://melpa.org/packages/"))' \
            --eval '(package-refresh-contents)' \
            --eval '(package-install (quote plz))'
      - name: Test
        run: make test
      - name: Compile
        run: make compile
